version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

jobs:
  install-and-test:
    executor: python-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-deps-{{ checksum "requirements.txt" }}
            - pip-deps-

      - run:
          name: Create and activate virtualenv
          command: |
            python -m venv venv
            . venv/bin/activate
            python -V

      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - save_cache:
          paths:
            - ~/.cache/pip
            - ~/repo/venv
          key: pip-deps-{{ checksum "requirements.txt" }}

      - run:
          name: Run linter (flake8)
          command: |
            . venv/bin/activate
            if command -v flake8 >/dev/null 2>&1; then
              flake8 || true
            else
              echo "flake8 not installed; skipping lint"
            fi

      - run:
          name: Run tests (pytest)
          command: |
            . venv/bin/activate
            export PYTHONPATH=.
            mkdir -p test-reports
            if command -v pytest >/dev/null 2>&1; then
              pytest --junitxml=test-reports/results.xml -v || true
            else
              echo "pytest not installed; skipping tests"
            fi

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Deploy preparation
          command: echo "🚀 Deployment preparation complete"
      - run:
          name: Deploy
          command: echo "🚀 Your actual deploy command goes here"

workflows:
  test_and_deploy:
    jobs:
      - install-and-test
      - deploy:
          requires:
            - install-and-test
          filters:
            branches:
              only: main
